name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Release cloutility-api-client
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["amd64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: ${{ GITHUB_REF_NAME }}
      - name: Release binarys
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "cloutility-api-client"
